import { createFileRoute } from "@tanstack/react-router";import { useState } from "react";import { CalendarPlus, Download } from "lucide-react";import { Button } from "@/components/ui/button";import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";import { SloganMark, detailLinkClass,eventCategoryClass,PageIntro,PhotoPlaceholder,SketchArrow } from "@/components/site";import { useSuspenseQuery } from "@tanstack/react-query";import { siteDataQuery,toUiEvents,type UiEvent } from "@/lib/site-data";import { downloadIcs,googleCalendarUrl } from "@/lib/calendar";
export const Route=createFileRoute("/events")({head:()=>({meta:[{title:"Etkinlikler — YZT · Geleceği Birlikte Şekillendirelim"},{name:"description",content:"YZT yaklaşan ve geçmiş etkinlikleri."},{property:"og:title",content:"Etkinlikler — YZT"},{property:"og:description",content:"Seminer, atölye, söyleşi ve teknik geziler."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),loader:({context})=>context.queryClient.ensureQueryData(siteDataQuery),component:Events});

function AddToCalendar({ event, compact=false }: { event: UiEvent; compact?: boolean }) {
  return <div className={`calendar-add ${compact?"calendar-add-compact":""}`}>
    <span className="calendar-add-label"><CalendarPlus className="size-3.5" aria-hidden="true"/>Takvime ekle</span>
    <div className="calendar-add-actions">
      <a href={googleCalendarUrl(event)} target="_blank" rel="noreferrer" className="calendar-add-btn">Google Takvim</a>
      <button type="button" onClick={()=>downloadIcs(event)} className="calendar-add-btn">Apple / Outlook <Download className="size-3.5" aria-hidden="true"/></button>
    </div>
  </div>;
}

 function Events(){const {data}=useSuspenseQuery(siteDataQuery);const events=toUiEvents(data.events);const [filter,setFilter]=useState("Tümü");const shown=filter==="Tümü"?events:events.filter(e=>e.status===filter);return <><PageIntro eyebrow="Etkinlikler · 01" title="Dinle, dene, birlikte üret."><p>Seminerlerden teknik gezilere kadar her buluşma yeni bir soru ve yeni bir bağlantı için.</p></PageIntro><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mb-10 flex flex-wrap items-center gap-2 border-b border-brand-mid pb-5" aria-label="Etkinlik filtresi"><span className="section-marker mr-auto">02 / Takvim</span>{["Tümü","Yaklaşan","Geçmiş"].map(x=><Button key={x} variant={filter===x?"default":"outline"} onClick={()=>setFilter(x)}>{x}</Button>)}</div><div className="grid gap-x-7 gap-y-16 md:grid-cols-2 lg:grid-cols-3">{shown.map((e,i)=><article key={e.id} data-tilt="event" className={`premium-tilt event-preview ${eventCategoryClass(e.tag)}`}>{e.image?<img src={e.image} alt={`${e.title} etkinliği`} className="aspect-[4/3] w-full border border-foreground object-cover" loading="lazy"/>:<PhotoPlaceholder label={`${e.title} etkinliği`} index={i}/>}<div className="mt-5 flex items-center gap-3 text-xs font-bold uppercase"><span className="text-primary">{e.tag}</span><span className="text-brand-dark">{e.date}</span></div><h2 className="mt-3 font-display text-3xl">{e.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{e.desc}</p><Dialog><DialogTrigger asChild><Button variant="link" className={`mt-4 ${detailLinkClass}`}>Detay <SketchArrow className="transition-transform group-hover:translate-x-1"/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle className="font-display text-3xl">{e.title}</DialogTitle><DialogDescription className="pt-2 leading-6">{e.date}{e.time?` · ${e.time}`:""}{e.location?` · ${e.location}`:""} · {e.tag}</DialogDescription></DialogHeader>{e.image?<img src={e.image} alt="" className="aspect-[4/3] w-full object-cover"/>:<PhotoPlaceholder label={`${e.title} etkinliği`} index={i}/>}<p className="leading-7 text-muted-foreground">{e.desc} Program ve katılım bilgileri etkinlik tarihinden önce Instagram hesabımızda paylaşılacaktır.</p>{e.status==="Yaklaşan"&&<AddToCalendar event={e}/>}</DialogContent></Dialog>{e.status==="Yaklaşan"&&<AddToCalendar event={e} compact/>}</article>)}</div></section><SloganMark/></>}
