import { FaqList, SponsorCta } from "@/components/extra-blocks";
import { createFileRoute,Link } from "@tanstack/react-router";import { ArrowRight,Clock3,Instagram } from "lucide-react";import { Fragment,useCallback,useEffect,useRef,useState,type PointerEvent } from "react";import { Button } from "@/components/ui/button";import { Marquee, ArrowLink,DecorativeMotif,detailLinkClass,eventCategoryClass,PhotoPlaceholder,SectionHeading,SketchArrow } from "@/components/site";import { useSuspenseQuery } from "@tanstack/react-query";import { siteDataQuery,toUiEvents,nextEvent,formatTrDate,dailyFactIndex,istanbulDateKey } from "@/lib/site-data";
import { launchJoinConfetti } from "@/components/join-confetti";
import { InstaPulse } from "@/components/insta-pulse";

import { useSiteText } from "@/lib/site-text";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"YZT — Geleceği Birlikte Şekillendirelim"},{name:"description",content:"Geleceği birlikte şekillendirelim — merak eden, üreten ve paylaşan Kırıkkale Üniversitesi öğrencileri."},{property:"og:title",content:"YZT — Yapay Zeka Topluluğu"},{property:"og:description",content:"Geleceği birlikte şekillendirelim — Kırıkkale Üniversitesi Yapay Zeka Topluluğu."},{property:"og:image",content:"https://kkuyzt.lovable.app/og-image.jpg"},{property:"og:image:width",content:"1200"},{property:"og:image:height",content:"630"},{name:"twitter:image",content:"https://kkuyzt.lovable.app/og-image.jpg"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),loader:({context})=>context.queryClient.ensureQueryData(siteDataQuery),component:Home});
declare module "react"{namespace JSX{interface IntrinsicElements{"behold-widget":{["feed-id"]:string}}}}
function BeholdFeed(){useEffect(()=>{const w=window as unknown as {__bhldScript?:boolean};if(w.__bhldScript)return;w.__bhldScript=true;const s=document.createElement("script");s.type="module";s.src="https://w.behold.so/widget.js";document.head.append(s)},[]);return <behold-widget feed-id="0ljmPNpOP6GlRdpiHIXz"/>}
function Countdown({target}:{target:number}){const [d,setD]=useState([0,0,0,0]);useEffect(()=>{const run=()=>{const x=Math.max(0,target-Date.now());setD([Math.floor(x/86400000),Math.floor(x/3600000)%24,Math.floor(x/60000)%60,Math.floor(x/1000)%60])};run();const id=setInterval(run,1000);return()=>clearInterval(id)},[target]);return <div className="countdown-collage">{d.map((x,i)=><div key={i} className={`countdown-sticker countdown-sticker-${i+1}`}><strong key={`${i}-${x}`} className="countdown-digit">{String(x).padStart(2,"0")}</strong><span>{["Gün","Saat","Dakika","Saniye"][i]}</span></div>)}</div>}
function DailyFact({facts}:{facts:{id:string;content:string}[]}){const [day,setDay]=useState<string|null>(null);useEffect(()=>{const refresh=()=>setDay(istanbulDateKey());refresh();const timer=window.setInterval(refresh,30000);return()=>window.clearInterval(timer)},[]);const index=day?dailyFactIndex(day,facts.length):-1;const fact=facts[index];if(!fact)return null;return <section aria-labelledby="daily-fact-title" className="border-y border-border bg-muted px-5 py-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-2 sm:flex-row sm:items-baseline sm:gap-6"><h2 id="daily-fact-title" className="shrink-0 text-sm font-semibold text-brand-dark">Günün bilgisi</h2><p className="max-w-4xl text-sm leading-6 text-foreground">{fact.content}</p></div></section>}
type Poster=Record<string,string|number>|null;const DEFAULT_POSTER={kicker:"YZT sunar",season:"26—27",title:"Topluluk Tanışması",subtitle:"Yeni dönem / İlk buluşma",date_text:"15 Eylül",time_text:"19.00",door_text:"Kapılar 18.30",place_text:"Swallowe",footer_left:"Kırıkkale Üniversitesi",footer_right:"01 / Açılış"};
function EventCollage({poster}:{poster:Poster}){const p={...DEFAULT_POSTER,...(poster??{})} as typeof DEFAULT_POSTER;const words=p.title.trim().split(/\s+/);const titleLast=words.length>1?words.pop()!:words[0]??"";const titleFirst=words.length&&words[0]!==titleLast?words.join(" "):"";const sub=p.subtitle.split("/").map(x=>x.trim()).filter(Boolean);const ref=useRef<HTMLDivElement>(null);const move=(event:PointerEvent<HTMLDivElement>)=>{const box=event.currentTarget.getBoundingClientRect();const x=(event.clientX-box.left)/box.width-.5;const y=(event.clientY-box.top)/box.height-.5;ref.current?.style.setProperty("--mx",String(x));ref.current?.style.setProperty("--my",String(y))};const reset=()=>{ref.current?.style.setProperty("--mx","0");ref.current?.style.setProperty("--my","0")};return <div ref={ref} onPointerMove={move} onPointerLeave={reset} className="event-collage" aria-label={`${p.title} etkinliği: ${p.date_text}, ${p.time_text}, ${p.place_text}`}><div className="event-collage-grain"/><div className="event-collage-lines"/><p className="event-collage-kicker">{p.kicker} <span>{p.season}</span></p><div className="event-collage-title">{titleFirst&&<span>{titleFirst}</span>}<strong>{titleLast}</strong></div><div className="event-collage-mark" aria-hidden="true"><svg viewBox="0 0 100 100" fill="none"><path d="M18 54C24 28 41 17 57 21c16 3 27 17 25 34-2 18-18 29-36 25-17-4-29-20-24-36 5-15 23-23 37-16 13 7 17 25 7 36-9 11-27 9-32-4-5-12 5-25 18-24 11 1 17 14 10 23"/><path d="M13 18l14 7M74 11l-4 15M83 82l-12-7"/></svg></div><p className="event-collage-note">{sub.map((x,i)=><Fragment key={i}>{i>0&&<br/>}{x}</Fragment>)}</p><div className="event-sticker event-sticker-date"><span>Tarih</span><strong>{p.date_text}</strong></div><div className="event-sticker event-sticker-time"><Clock3 className="event-sticker-time-icon" aria-hidden="true"/><span>Saat</span><strong>{p.time_text}</strong><small>{p.door_text}</small></div><div className="event-sticker event-sticker-place"><span>Yer</span><strong>{p.place_text}</strong></div><div className="event-collage-footer"><span>{p.footer_left}</span><span>{p.footer_right}</span></div></div>}
type IntroPhase="closed"|"opening"|"typing"|"done";
const RING_WORD="birlikte";
function TypedTitle({title,typed,ring}:{title:string;typed:string;ring:boolean}){
  const at=title.indexOf(RING_WORD);
  if(at<0)return <>{typed}</>;
  const end=at+RING_WORD.length;
  const before=typed.slice(0,Math.min(typed.length,at));
  const word=typed.length>at?typed.slice(at,Math.min(typed.length,end)):"";
  const after=typed.length>end?typed.slice(end).replace(/^\s+/,""):"";
  return <>{before}{word?<span className="hero-ring-word">{word}<svg className={ring?"hero-ring is-drawn":"hero-ring"} viewBox="0 0 250 22" preserveAspectRatio="none" aria-hidden="true"><path d="M6 11C46 5 118 4 176 7c26 1 52 3 68 6"/><path className="hero-ring-second" d="M14 18C58 13 122 12 178 14c24 1 44 2 56 4"/></svg></span>:null}{typed.length>end?<br/>:null}{after}</>;
}
function HomeIntro({title,onComplete}:{title:string;onComplete:()=>void}){const [phase,setPhase]=useState<IntroPhase>("closed");const [typed,setTyped]=useState("");const [drawn,setDrawn]=useState(false);useEffect(()=>{const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const seen=window.sessionStorage.getItem("yzt-home-intro-seen")==="1";if(reduced||seen){setPhase("done");setTyped(title);setDrawn(true);onComplete();return}window.sessionStorage.setItem("yzt-home-intro-seen","1");const timers:number[]=[];const frame=window.requestAnimationFrame(()=>setPhase("opening"));let interval=0;timers.push(window.setTimeout(()=>{setPhase("typing");let i=0;interval=window.setInterval(()=>{i+=1;setTyped(title.slice(0,i));if(i>=title.length){window.clearInterval(interval);setPhase("done");onComplete();timers.push(window.setTimeout(()=>setDrawn(true),320));}},58)},620));return()=>{window.cancelAnimationFrame(frame);if(interval)window.clearInterval(interval);timers.forEach(timer=>window.clearTimeout(timer));}},[title,onComplete]);const complete=phase==="done";const typing=phase==="typing";return <><div className={`hero-intro-copy ${complete?"hero-intro-copy-complete":""}`}><p className="hero-kicker">Kırıkkale Üniversitesi <span aria-hidden="true">·</span> Öğrenci Topluluğu</p><h1 aria-label={title} className={`hero-intro-title relative mt-6 font-display text-5xl leading-[.95] sm:text-6xl lg:text-7xl xl:text-[5.25rem] ${typing||complete?"is-settled":""}`}><span aria-hidden="true" className="invisible block"><TypedTitle title={title} typed={title} ring={drawn}/></span><span aria-hidden="true" className="absolute inset-0"><TypedTitle title={title} typed={typed} ring={drawn}/>{typing&&<span className="hero-typing-caret" aria-hidden="true"/>}</span></h1></div>{(phase==="closed"||phase==="opening")&&<div className={`site-intro-curtain ${phase==="opening"?"is-opening":""}`} aria-hidden="true"><span className="site-intro-panel site-intro-panel-left"/><span className="site-intro-panel site-intro-panel-right"/></div>}</>}
function Home(){const {data}=useSuspenseQuery(siteDataQuery);const t=useSiteText();const [introComplete,setIntroComplete]=useState(false);const finishIntro=useCallback(()=>setIntroComplete(true),[]);const events=toUiEvents(data.events);const past=events.filter(e=>e.status==="Geçmiş").slice(0,3);const next=nextEvent(events);const nextTarget=next?new Date(`${next.iso}T${/^\d{1,2}[:.]\d{2}$/.test(next.time)?next.time.replace(".",":").padStart(5,"0"):"00:00"}:00+03:00`).getTime():0;return <>
<section className="min-h-[92vh] bg-background pt-32"><div className="hero-content mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-10 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,.8fr)] lg:items-center"><div className="min-w-0"><HomeIntro title={t.home_hero_title} onComplete={finishIntro}/><div className={`hero-intro-details ${introComplete?"is-visible":""}`}><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">{t.home_hero_text}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/join" onClick={(event) => launchJoinConfetti(event.currentTarget)}>Bize Katıl <ArrowRight/></Link></Button><Button asChild variant="outline" size="lg"><a href={t.instagramUrl} target="_blank" rel="noreferrer"><Instagram/>Instagram'da Takip Et</a></Button></div></div></div><div className={`hero-intro-poster ${introComplete?"is-visible":""}`}><EventCollage poster={data.poster}/></div></div><div className={`hero-intro-details mt-10 ${introComplete?"is-visible":""}`}><InstaPulse/></div><div className={`hero-intro-details mt-4 flex items-center gap-4 border-t border-border py-5 text-xs font-bold uppercase ${introComplete?"is-visible":""}`}><span className="text-primary">Aşağı kaydır</span><span className="h-px flex-1 bg-border"/><span>Kırıkkale · TR</span></div></div></section>
<Marquee/><DailyFact facts={data.facts}/>
<section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-6 md:grid-cols-[1.2fr_.8fr] md:items-end"><h2 className="font-display text-5xl leading-tight md:text-7xl">Masadan, sahneden, yoldan.</h2><p className="max-w-md leading-7 text-muted-foreground md:justify-self-end">Topluluğun son buluşmalarından kısa notlar.</p></div><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{past.map((e,i)=><article key={e.id} data-tilt="event" className={`premium-tilt event-preview ${eventCategoryClass(e.tag)} ${i===1?"event-card-offset":""}`}>{e.image?<img src={e.image} alt={e.title} className="aspect-[4/3] w-full border border-foreground object-cover" loading="lazy"/>:<PhotoPlaceholder label={e.title} index={i}/>}<p className="mt-5 text-xs font-bold uppercase"><span className="text-primary">{e.tag}</span> <span className="text-brand-dark">· {e.date}</span></p><h3 className="mt-3 font-sans text-3xl">{e.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{e.desc}</p><div className="mt-5"><ArrowLink to="/events">Detay</ArrowLink></div></article>)}</div></section>
<section className="motif-section bg-muted py-20 lg:py-28"><DecorativeMotif variant="neuron" position="right"/><div className="motif-content mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="Topluluk" title={t.home_features_title} align="right"/><div className="mt-14 grid border border-foreground md:grid-cols-2">{[["01","Hakkımızda",t.home_feat_about,"/about"],["02","Takımımız",t.home_feat_team,"/team"],["03","Etkinlikler",t.home_feat_events,"/events"],["04","İş Ortakları",t.home_feat_partners,"/partners"]].map((x,i)=><Link key={x[0]} to={x[3] as "/about"} className={`feature-panel group bg-background p-7 transition-colors hover:bg-foreground hover:text-background md:p-10 ${i%2===0?"md:border-r border-foreground":""} ${i<2?"border-b border-foreground":""}`}><h3 className="font-sans text-3xl font-semibold">{x[1]}</h3><div className="mt-4 flex items-end justify-between gap-5"><p className="text-sm text-muted-foreground group-hover:text-background/65">{x[2]}</p><SketchArrow className="shrink-0 text-primary transition-transform group-hover:translate-x-1"/></div></Link>)}</div></div></section>
<section className="motif-section bg-foreground py-20 text-background lg:py-28"><DecorativeMotif variant="star" tone="cream" position="left"/><div className="motif-content mx-auto max-w-7xl px-5 lg:px-8"><div className="mb-12 grid gap-8 md:grid-cols-2 md:items-end"><div><p className="section-kicker text-background/65">Sıradaki etkinlik</p><h2 className="mt-5 font-display text-5xl md:text-7xl">{next?.title ?? "Yakında duyurulacak"}</h2></div>{next&&<div className="border-r-2 border-primary pr-5 md:text-right"><p className="font-bold">{next.date}{next.time?` · ${next.time}`:""}</p>{next.location&&<p className="mt-2 text-sm text-background/55">{next.location}</p>}</div>}</div><Countdown target={nextTarget}/><div className="mt-10"><Button asChild><Link to="/events">Etkinliği incele <ArrowRight/></Link></Button></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="@kku_yzt" title="Topluluğun içinden." copy="Etkinlik anları, duyurular ve kampüsten notlar için bizi Instagram’da takip et." align="right"/><div className="mt-12 border-t-2 border-primary pt-4">{data.posts.length?<div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{data.posts.map((p,i)=>{const inner=<><img src={p.image_url} alt={p.caption||"Instagram paylaşımı"} className="aspect-square w-full object-cover" loading="lazy"/><div className="mt-3 flex items-baseline justify-between gap-2 text-xs"><span className="line-clamp-1 font-semibold">{p.caption}</span><span className="shrink-0 text-muted-foreground">{formatTrDate(p.post_date)}</span></div></>;return p.link_url?<a key={p.id} href={p.link_url} target="_blank" rel="noreferrer" className={`block border border-foreground p-2 transition-transform hover:-translate-y-1 ${i%2?"md:translate-y-4":""}`}>{inner}</a>:<div key={p.id} className={`border border-foreground p-2 ${i%2?"md:translate-y-4":""}`}>{inner}</div>})}</div>:<BeholdFeed/>}</div><div className="mt-8 flex md:justify-end"><Button asChild variant="outline"><a href={t.instagramUrl} target="_blank" rel="noreferrer"><Instagram/>@{t.instagram_handle} hesabını takip et</a></Button></div></section><section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8 lg:pb-28">
  <div className="grid gap-8 border-t border-foreground pt-10 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="section-kicker">Site içinde</p><h2 className="mt-3 font-display text-4xl leading-tight md:text-6xl">Biraz daha yakından.</h2></div><p className="max-w-xl leading-7 text-muted-foreground lg:justify-self-end">Üyelik avantajlarından kısa bir molaya, topluluğun ortak duruşuna uzanan üç ayrı durak.</p></div>
  <div className="mt-12 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-start">
    <Link to="/yzt-card" className="group border border-foreground bg-muted p-7 md:p-10"><p className="text-sm font-semibold text-brand-dark">Üyelere özel</p><h3 className="mt-4 text-4xl font-semibold">YZT Kart</h3><p className="mt-4 max-w-lg leading-7 text-muted-foreground">Anlaşmalı iş ortaklarındaki güncel öğrenci indirimlerinden yararlan; kartını buradan iste.</p><span className={`${detailLinkClass} mt-8`}>Kartı incele <SketchArrow className="transition-transform group-hover:translate-x-1"/></span></Link>
    <div className="border-t border-brand-mid pt-6 lg:mt-16"><p className="text-sm text-muted-foreground">Kısa bir mola</p><Link to="/games" className="group mt-2 flex items-end justify-between gap-5"><div><h3 className="text-3xl font-semibold">Mini Oyunlar</h3><p className="mt-3 max-w-md leading-7 text-muted-foreground">Günün kelimesini çöz, yapay zekâyı evrimleştir veya insanla makineyi ayırt etmeyi dene.</p></div><SketchArrow className="shrink-0 text-brand-dark transition-transform group-hover:translate-x-1"/></Link></div>
  </div>
  <Link to="/manifesto" className="group mt-12 block bg-brand-dark px-7 py-10 text-background md:px-12 md:py-14"><p className="text-sm font-semibold text-brand-pale">Manifesto</p><p className="mt-6 max-w-5xl font-display text-4xl leading-tight md:text-6xl">Merak ederiz. Deneriz. Üretiriz. Paylaşırız. Birlikte büyürüz.</p><span className="mt-8 inline-flex items-center gap-3 border-b border-brand-pale pb-1 text-sm font-semibold text-brand-pale">Manifestoyu oku <SketchArrow className="transition-transform group-hover:translate-x-1"/></span></Link>
</section>
<section className="bg-muted py-20 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.72fr_1.28fr] lg:px-8"><div><h2 className="font-display text-5xl leading-tight">Katılmadan önce.</h2><div className="mt-8"><Link to="/faq" className={detailLinkClass}>Tüm soruları gör <ArrowRight className="size-4"/></Link></div></div><FaqList limit={4}/></div></section><SponsorCta/></>}
