import { createFileRoute } from "@tanstack/react-router";
import { BadgePercent, type LucideIcon } from "lucide-react";
import { useSuspenseQuery } from "@tanstack/react-query";
import { siteDataQuery } from "@/lib/site-data";
import { partnerIcon } from "@/lib/partner-icons";
import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SloganMark, PageIntro, detailLinkClass } from "@/components/site";

export const Route=createFileRoute("/partners")({head:()=>({meta:[{title:"İş Ortakları — YZT · Geleceği Birlikte Şekillendirelim"},{name:"description",content:"YZT üyelerine avantaj sağlayan iş ortakları."},{property:"og:title",content:"İş Ortakları — YZT"},{property:"og:description",content:"Topluluğumuzu destekleyen yerel iş ortakları."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),loader:({context})=>context.queryClient.ensureQueryData(siteDataQuery),errorComponent:()=><p className="p-10">İçerik yüklenemedi.</p>,notFoundComponent:()=><p className="p-10">Bulunamadı.</p>,component:Partners});

const accents=[
  {badge:"bg-brand-light text-background",line:"bg-brand-light",icon:"text-brand-light",position:"top-6 right-6 rotate-3"},
  {badge:"bg-brand-mid text-background",line:"bg-brand-mid",icon:"text-brand-mid",position:"top-6 left-6 -rotate-2"},
  {badge:"bg-brand-dark text-background",line:"bg-brand-dark",icon:"text-brand-dark",position:"top-6 right-6 rotate-2"},
  {badge:"bg-brand-pale text-brand-dark",line:"bg-brand-light",icon:"text-brand-light",position:"top-8 right-8 -rotate-3"},
  {badge:"bg-brand-light text-background",line:"bg-brand-dark",icon:"text-brand-dark",position:"top-6 left-6 rotate-3"},
  {badge:"bg-brand-dark text-background",line:"bg-brand-mid",icon:"text-brand-mid",position:"top-6 left-1/2 -translate-x-1/2 -rotate-2"},
] as const;

function PartnerMark({name,category,Icon,index,image}:{name:string;category:string;Icon:LucideIcon;index:number;image:string|null}){const accent=accents[index%accents.length] ?? accents[0];return <div role="img" aria-label={`${name} logo alanı`} className={`relative grid aspect-[3/2] place-items-center overflow-hidden border border-foreground bg-muted p-6 text-center ${index%2?"border-b-4":"border-t-4"}`}><div className={`absolute ${index%2?"right-5 top-5":"bottom-5 left-5"} grid grid-cols-3 gap-1 opacity-35`} aria-hidden="true">{Array.from({length:9},(_,dot)=><i key={dot} className={`size-1 ${accent.line}`}/>)}</div><span className={`absolute z-10 px-2 py-1 text-[10px] font-bold uppercase ${accent.badge} ${accent.position}`}>{String(index+1).padStart(2,"0")} · {category}</span>{image?<img src={image} alt="" className="absolute inset-0 size-full object-cover"/>:<Icon className={`size-12 ${accent.icon}`} strokeWidth={1.35}/>}<span className="absolute bottom-4 right-4 max-w-[55%] font-display text-lg font-semibold leading-tight text-muted-foreground">{name}</span></div>}

function Partners(){const {data}=useSuspenseQuery(siteDataQuery);const partners=data.partners;const lastRow=partners.length-(partners.length%3||3);return <><PageIntro eyebrow="İş Ortakları · 01" title="Yerel destek, ortak değer."><p>Topluluğumuzun üretim alanını büyüten ve üyelerimize günlük hayatta küçük avantajlar sağlayan destekçilerimiz.</p></PageIntro><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mb-10 flex justify-end"><span className="section-marker">02 / {partners.length} durak</span></div><div className="grid border border-foreground sm:grid-cols-2 lg:grid-cols-3">{partners.map((p,index)=>{const {name,description,category}=p;const Icon=partnerIcon(p.icon);const accent=accents[index%accents.length] ?? accents[0];return <article key={p.id} className={`relative bg-background p-6 ${index%3<2?'lg:border-r border-foreground':''} border-foreground ${index<partners.length-1?'border-b':''} ${index>=lastRow?'lg:border-b-0':''}`}><PartnerMark name={name} category={category} Icon={Icon} index={index} image={p.image_url}/><div className={`mt-6 flex gap-3 ${index%2?"flex-row-reverse text-right":""}`}><BadgePercent className={`mt-0.5 size-5 shrink-0 ${accent.icon}`} strokeWidth={1.5}/><div><h2 className="font-display text-2xl">{name}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p><span className={`mt-4 block h-px w-12 ${accent.line} ${index%2?"ml-auto":""}`}/></div></div></article>})}</div><div className="mt-8 flex flex-col items-start justify-between gap-5 border-l-2 border-primary bg-muted p-6 md:flex-row md:items-center"><p className="max-w-2xl text-sm leading-6 text-muted-foreground">Avantajlardan YZT Kart ile yararlanabilirsin. Koşullar işletmeye göre değişebilir.</p><Link to="/yzt-card" className={detailLinkClass}>YZT Kart’a başvur <ArrowRight className="size-4"/></Link></div><div className="mt-12 flex flex-col gap-4 border border-foreground bg-brand-pale p-8 md:flex-row md:items-center md:justify-between"><p className="font-display text-2xl">Şirketiniz topluluğa destek olmak mı istiyor?</p><Link to="/sponsor" className={detailLinkClass}>Sponsorluk seçenekleri <ArrowRight className="size-4"/></Link></div></section><SloganMark/></>}